mysql:
    dsn: yoomall:yoomall@tcp(127.0.0.1:3306)/yoomall?charset=utf8mb4&parseTime=True&loc=Local
DEBUG: true
http:
    host: 127.0.0.1
    port: 8900
storage_path: ./storage


dtk: 
    app_key: xx
    app_secret: xxx
    app_url: https://openapi.dataoke.com/api/

jutuike:
    pub_id: xx
    api_key: xxxx
    jtk_url: http://api.jutuike.com/


vite:
    url: http://127.0.0.1:5173
    debug: false
    build_dir: ./public 